
name: Feature request
description: Suggest an idea for this project
title: '[OS.Client]Feature: '
# labels: ''
# assignees: ''
body:
  - type: dropdown
    validations:
      required: true
    attributes:
      label: videoduplicatefinder version
      description: |
        What is the version number of the release you're using?
        Please note - if you find yourself picking anything besides the latest release, stop now,
        update to the latest release, and confirm your issue has been addressed.
      options:
        - "2.1.0"
        - "Something older (Stop now, update to the latest release, & check if it does what you want)"

  - type: dropdown
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Windows
        - OSX Mac
        - Linux
        - Other?
  - type: dropdown
    validations:
      required: true
    
    attributes:      
      label: Client Type
      description: Which client are you trying to use?
      options:
        - Windows only GUI (Only in versions <2.1.0)
        - Cross platform GUI (Versions >= 2.1.0)
        - Console
        - Web
  - type: textarea
    attributes:
      label: Describe what you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
